"use client";

import { useAuth } from "@/context/AuthContext";
import RecommendationCard from "@/components/RecommendationCard";
import type { Recommendation } from "@/types";

// Mock recommendations — later powered by AI engine
const mockRecommendations: Recommendation[] = [
  {
    product: "Milk (1L)",
    issue: "High expiry risk — 50 units expiring in 2 days",
    recommendation:
      "Transfer 20 units to Branch 9 (Pune) because their daily demand is 25/day but inventory is only 10.",
  },
  {
    product: "Bread (White)",
    issue: "High expiry risk — 80 units expiring tomorrow",
    recommendation:
      "Run a 30% flash discount on bread at your branch. Also transfer 30 units to Branch 2 (Andheri) where stock is low.",
  },
  {
    product: "Fresh Juice (500ml)",
    issue: "High expiry risk — 20 units expiring in 3 days",
    recommendation:
      "Bundle with Yogurt for a combo offer. Branch 1 (Mumbai Central) has high juice demand; transfer 10 units.",
  },
];

export default function RecommendationsPage() {
  const { profile } = useAuth();

  if (!profile) return null;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Recommendations</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          AI-powered actions to reduce waste at{" "}
          <span className="font-medium text-foreground">{profile.branch}</span>
        </p>
      </div>

      {/* Info banner */}
      <div className="rounded-xl border border-primary/20 bg-primary/10 px-5 py-4">
        <p className="text-sm text-foreground">
          <span className="font-semibold">Smart Insights:</span> These recommendations are generated by
          cross-referencing your store&apos;s expiry data with demand patterns from other{" "}
          <strong>{profile.company}</strong> branches.
        </p>
      </div>

      {/* Cards */}
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        {mockRecommendations.map((rec, i) => (
          <RecommendationCard key={i} data={rec} />
        ))}
      </div>
    </div>
  );
}
