"use client";

import { useMemo } from "react";
import { useAuth } from "@/context/AuthContext";
import RecommendationCard from "@/components/RecommendationCard";
import RecommendationSummary from "@/components/RecommendationSummary";
import {
  getMockInventory,
  getMockBranchDemand,
  generateRecommendations,
} from "@/lib/recommendationEngine";

export default function RecommendationsPage() {
  const { profile } = useAuth();

  const recommendations = useMemo(() => {
    if (!profile) return [];
    const inventory = getMockInventory(profile.branch);
    const demand = getMockBranchDemand(profile.branch);
    return generateRecommendations(inventory, demand);
  }, [profile]);

  if (!profile) return null;

  const highPriority = recommendations.filter((r) => r.priority === "high").length;
  const wasteReduction = recommendations.reduce((sum, r) => sum + r.units, 0);

  return (
    <div className="space-y-8">
      {/* ── Page Header ── */}
      <div>
        <h1 className="text-2xl font-bold text-foreground">Recommendations</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {profile.company} &mdash;{" "}
          <span className="font-medium text-foreground">{profile.branch}</span>
        </p>
      </div>

      {/* ── Summary KPI Cards ── */}
      <RecommendationSummary
        total={recommendations.length}
        highPriority={highPriority}
        wasteReduction={wasteReduction}
      />

      {/* ── Info Banner ── */}
      <div className="rounded-xl border border-primary/20 bg-primary/10 px-5 py-4">
        <p className="text-sm text-foreground">
          <span className="font-semibold">Smart Insights:</span> These recommendations are
          generated by cross-referencing your store&apos;s expiry data with demand patterns
          from other <strong>{profile.company}</strong> branches.
        </p>
      </div>

      {/* ── Recommendation Cards ── */}
      {recommendations.length > 0 ? (
        <div className="grid gap-6 lg:grid-cols-2">
          {recommendations.map((rec) => (
            <RecommendationCard key={rec.id} data={rec} />
          ))}
        </div>
      ) : (
        <div className="rounded-xl border border-border bg-card p-10 text-center">
          <p className="text-muted-foreground">
            No recommendations at this time. Your inventory looks healthy!
          </p>
        </div>
      )}
    </div>
  );
}
